import streamlit as st
from datetime import datetime, timedelta
from database import (
    get_revenue_and_cost, get_daily_sales_summary,
    get_expiring_items, get_expired_items,
    get_low_stock_items, get_waste_summary,
    get_menu_items, get_recipes_for_item, get_inventory
)
from ai_engine import generate_weekly_report


def render(global_date=None, global_date_str=None):
    st.title("🤖 AI Reports")

    with st.expander("ℹ️ **What is this page?** (click to read)", expanded=False):
        st.markdown(
            """
            This is where you get **AI-powered reports** about how your cafe performed.

            **How to use it:**
            1. The report covers all sales from **March 1 up to the date you selected in the sidebar**
            2. Click the "Generate Report" button
            3. The AI will crunch your sales, waste, and stock data and give you a detailed report

            **What the report covers:**
            - 💰 Revenue, cost, and profit breakdown
            - 🏆 Your top-selling and worst-performing items
            - 📅 Weekend vs weekday patterns (the AI detects sales spikes on Sat/Sun)
            - ⚠️ Expiry warnings – what's about to go bad and how to use it up
            - 📦 Restock recommendations – what to reorder and how much
            - 💡 Creative suggestions – combo deals, new items, etc.

            **AI + Fallback:** The report is generated by AI (via OpenRouter – tries GPT-4o-mini,
            then Claude, then Gemini). If all AI models fail (no internet, no API key, etc.),
            a **built-in rule-based engine** generates the same report using Python calculations.
            You always get a result, no matter what.
            """
        )

    if global_date is None:
        global_date = datetime(2026, 3, 20).date()
        global_date_str = "2026-03-20"

    start_date = "2026-03-01"
    end_date = global_date_str
    period_label = f"March 1 – {global_date.strftime('%B %d, %Y')} ({global_date.strftime('%A')})"

    st.markdown("---")

    with st.container(border=True):
        st.markdown(f"### 📅 Report Period: **{period_label}**")
        st.caption("This covers all sales data from the start of March up to the date selected in the sidebar.")

    import os
    has_key = bool(os.getenv("OPENROUTER_API_KEY", "").strip())
    if not has_key:
        st.info(
            "🔒 **No API key detected – fallback mode active.** "
            "The report will be generated using built-in rule-based analysis. "
            "To get AI-powered insights, clone this repo and add your OpenRouter API key to `.env`. "
            "We don't include API keys in production to prevent misuse on public deployments.",
            icon="ℹ️",
        )

    st.markdown("")

    generate_btn = st.button(
        f"🤖 Generate AI Report for sales till {global_date.strftime('%B %d')}",
        use_container_width=True,
        type="primary",
    )

    if generate_btn:
        import time

        progress_bar = st.progress(0)
        status_box = st.empty()

        # Step 1: Gather data
        status_box.info("📊 **Step 1/5:** Collecting your sales data...")
        time.sleep(0.5)
        revenue_data = get_revenue_and_cost(start_date, end_date)
        daily_summary = get_daily_sales_summary(start_date, end_date)
        progress_bar.progress(20)

        # Step 2: Analyze stock
        status_box.info("📦 **Step 2/5:** Checking stock levels and expiry dates...")
        time.sleep(0.5)
        expiring = get_expiring_items(end_date, within_days=7)
        expired = get_expired_items(end_date)
        low_stock = get_low_stock_items()
        progress_bar.progress(40)

        # Step 3: Waste + recipes + inventory
        status_box.info("🗑️ **Step 3/5:** Collecting waste, recipes, and inventory data...")
        time.sleep(0.5)
        waste = get_waste_summary(start_date, end_date)
        # Get recipes for cross-referencing
        menu_items = get_menu_items(active_only=True)
        recipes_data = []
        for item in menu_items:
            recs = get_recipes_for_item(item["id"])
            if recs:
                recipes_data.append({
                    "menu_item": item["name"],
                    "price": item["sell_price"],
                    "ingredients": [{"name": r["ingredient"], "qty": r["quantity_needed"], "unit": r["unit"]} for r in recs]
                })
        inventory = get_inventory()
        inventory_data = [{"name": i["name"], "qty": i["quantity"], "unit": i["unit"], "expiry": i["expiry_date"], "cost": i["cost_per_unit"]} for i in inventory]
        progress_bar.progress(60)

        # Step 4: Build report
        status_box.info("🧠 **Step 4/5:** AI is analyzing patterns and writing your report... (this may take a few seconds)")
        time.sleep(0.3)

        report_data = {
            "period": period_label,
            "total_revenue": revenue_data["total_revenue"],
            "total_cost": revenue_data["total_cost"],
            "total_profit": revenue_data["total_profit"],
            "top_sellers": revenue_data["items"][:10],
            "daily_summary": daily_summary,
            "expiring_items": [
                {"name": i["name"], "expiry_date": i["expiry_date"],
                 "quantity": i["quantity"], "unit": i["unit"]}
                for i in expiring
            ],
            "expired_items": [
                {"name": i["name"], "quantity": i["quantity"], "unit": i["unit"]}
                for i in expired
            ],
            "waste_log": waste,
            "low_stock": [
                {"name": i["name"], "quantity": i["quantity"], "unit": i["unit"]}
                for i in low_stock
            ],
            "recipes": recipes_data,
            "inventory": inventory_data,
        }

        result = generate_weekly_report(report_data)
        progress_bar.progress(90)

        # Step 5: Done
        if result["source"] == "ai":
            status_box.info("✨ **Step 5/5:** AI report ready! Formatting results...")
        else:
            status_box.info("📊 **Step 5/5:** AI was unavailable – fallback report generated! Formatting results...")
        time.sleep(0.5)
        progress_bar.progress(100)
        time.sleep(0.3)

        # Clear progress indicators
        progress_bar.empty()
        status_box.empty()

        # Display report
        st.markdown("---")

        # Show source badge
        if result["source"] == "ai":
            st.caption("🤖 This report was generated by AI – and remember, AI can make mistakes. Always verify important numbers before acting on them.")
        else:
            st.caption("📊 AI was unavailable. This report was generated using built-in rule-based analysis.")

        st.markdown(result["report"])

        # Quick stats
        st.markdown("---")
        st.subheader("📊 Quick Numbers")

        col1, col2, col3, col4 = st.columns(4)
        with col1:
            st.metric("Revenue", f"₹{revenue_data['total_revenue']:,.0f}")
        with col2:
            st.metric("Cost", f"₹{revenue_data['total_cost']:,.0f}")
        with col3:
            st.metric("Profit", f"₹{revenue_data['total_profit']:,.0f}")
        with col4:
            margin = revenue_data['total_profit'] / max(revenue_data['total_revenue'], 1) * 100
            st.metric("Margin", f"{margin:.1f}%")

    else:
        # Show placeholder
        st.markdown("---")
        st.markdown(
            """
            ### How it works:
            1. **Change the date** in the sidebar to set the report period (March 1 to that date)
            2. **Click 'Generate AI Report'** – the AI will analyze all your data for that period
            3. **Get actionable insights** – what sold well, what's wasting, what to reorder

            The report includes:
            - 💰 Revenue & profit breakdown
            - 🏆 Top selling and underperforming items
            - 📅 Weekend vs weekday patterns
            - ⚠️ Expiry and waste alerts
            - 📦 Restock recommendations
            - 💡 Creative suggestions to boost sales

            *If the AI service is down, you'll still get a complete rule-based report.*
            """
        )
